### ISSUE TITLE
Breadcrumb issue

### ISSUE THREAD

**Issue by DeeEmm** [nk-crew/docspress#25]
Hi Guys,

The breadcrumb incorrectly displays. It does not take the current path but instead uses 'doc'

Please see image below

<img width="1220" alt="Screen Shot 2020-09-13 at 3 46 50 pm" src="https://user-images.githubusercontent.com/3038710/93011828-14915a80-f5d9-11ea-869c-d9f73127e662.png">

**Comment by nk-o** [comment]
Hey.

What the title of your Documentation page?

![](https://user-images.githubusercontent.com/14810891/93686985-b70e7980-fac2-11ea-86a2-116714ca6bcd.png)
