### ISSUE TITLE
[Enhancement] Add categories on sidebar

### ISSUE THREAD

**Issue by rubengc** [nk-crew/docspress#31]
Hi there!

Actually on the archive page your documents gets separated by classes

On the single document sidebar, this causes that docs are not correctly ordered (because they have a custom order per category) and much more, they are not separated by the same categories

Would be awesome to have a setting to display the docs listing separated by categories too on the sidebar area

**Comment by nk-o** [comment]
added support for categories in sidebar https://github.com/nk-crew/docspress/commit/7ebe5ee796505ead0a82a2e4670d51d2dfec7060
