### ISSUE TITLE
Storefront theme - cannot disable sidebar

### ISSUE THREAD

**Issue by sandrodz** [nk-crew/docspress#39]
Storefront default Woo theme, I used template full-width for the page.
But page still loads sidebar css.

Any way to get rid of this sidebar class and css for doc archives? 

<img width="1492" alt="Screen Shot 2021-05-30 at 23 53 03" src="https://user-images.githubusercontent.com/8479569/120121279-d48ff900-c1a2-11eb-8d6a-a03c159a60c7.png">

**Comment by nk-o** [comment]
Not a plugin problem
